### ISSUE TITLE
Understand the independent probability

### ISSUE THREAD

**Issue by MichelleKuroda** [manuel-calzolari/sklearn-genetic#15]
Dear Manuel

Congratulations on your code, and thank you very much for sharing it.
I'm using it for geological issues, and I would like to understand the independent crossover probability and also independent mutation probability. I was studying these topics in GA papers, but I didn't find a definition.
Can you explain it to me?

Best regards,

Michelle.

**Comment by manuel-calzolari** [comment]
Hello Michelle,

they are the independent probability for each attribute to be exchanged or mutated. In this case, an attribute can be 0 (don't select the feature) or 1 (select the feature).

**Comment by MichelleKuroda** [comment]
Thank you very much, Manuel!

Your code is really useful. I'm writing a paper with results based on the selected attributes that I found using your code. 
I will cite you!

Best wishes,

Michelle.
