### ISSUE TITLE
elitism operator

### ISSUE THREAD

**Issue by MMX-1** [manuel-calzolari/sklearn-genetic#18]
hello,Apply elitism operator to selected individuals in this repository??

**Comment by MMX-1** [comment]
mutation operator and crossover operator both are uniform operator??

**Comment by manuel-calzolari** [comment]
At the moment there's not elitism, but I may implement it in the future (it makes sense especially when using the `n_gen_no_change` parameter). Selection is performed through "tournament selection".  

Mutation is a "flip bit" mutation. Crossover is a uniform crossover.

**Comment by MMX-1** [comment]
thank you

**Comment by MMX-1** [comment]
hello,I have already known "tournament size"parameter,but I don't know how many individuals you  select to   put into mate pool

**Comment by manuel-calzolari** [comment]
n individuals are selected from a pool of n (with replacement).

**Comment by MMX-1** [comment]
> n individuals are selected from a pool of n (with replacement).

thank u

**Comment by manuel-calzolari** [comment]
Elitism added with commit 3b39fe4, it will be in the next release.
