### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by DonBJ** [manuel-calzolari/sklearn-genetic#19]
Is this module limited to just classification? Can you perform regression with scoring set to rmse?

**Comment by manuel-calzolari** [comment]
Yes, you can

**Comment by manuel-calzolari** [comment]
You need to use something like `scoring="neg_root_mean_squared_error"`, see https://scikit-learn.org/stable/modules/model_evaluation.html#the-scoring-parameter-defining-model-evaluation-rules
