### ISSUE TITLE
Two values of data on avg, std, min and max columns 

### ISSUE THREAD

**Issue by caiocarvalho** [manuel-calzolari/sklearn-genetic#24]
Hello, thanks for sharing your code.

I am using it on a dataset to distinguish cancer versus normal patterns from mass-spectrometric data. 

I run the code and I am having a hard time understanding why there are two values of data on avg, std, min and max columns.
What does that mean?  I am attaching a printscreen to illustrate.

Thanks.

![WhatsApp Image 2021-08-06 at 12 43 59](https://user-images.githubusercontent.com/8854974/128544989-75803fc9-7cf4-4868-a335-667e2c03fdd0.jpeg)

**Comment by manuel-calzolari** [comment]
Hi! The first value is related to the score (e.g. accuracy), while the second value is related to the number of features.

**Comment by caiocarvalho** [comment]
Hi,
thank you for the quick reply!
