### ISSUE TITLE
Unable to freeze randomness to get the same results all the time

### ISSUE THREAD

**Issue by Tingweiftw** [manuel-calzolari/sklearn-genetic#26]
even after setting np.random.seed(xxx) the results are not predictable

**Comment by damiankucharski** [comment]
Hi @Tingweiftw, that is because this library in great part relies on the DEAP library (https://deap.readthedocs.io/en/master/) which uses the standard `random` module. To make your result reproducible you have to set both numpy and random seeds.

**Comment by manuel-calzolari** [comment]
I've added a comment about this to the README, see commit 0867df9.
