### ISSUE TITLE
Error when using “Group” cv instances

### ISSUE THREAD

**Issue by aretor** [manuel-calzolari/sklearn-genetic#28]
When Using a "Group" `sklearn` cross-validation object (in my case `GroupShuffleSplit`), the following error is raised

`ValueError: The groups parameter should not be None`

This issue might be related to [#7646](https://github.com/scikit-learn/scikit-learn/issues/7646) of sklearn repo.

I managed to fix it by adding the `groups` parameter to the `fit` method, as done in other `SearchCV` algorithms (e.g. [RandomizedSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html)).

I can send a pull request if needed.

**Comment by manuel-calzolari** [comment]
Hi @aretor! Yes, pull requests are welcome
