### ISSUE TITLE
How to get the scoring value

### ISSUE THREAD

**Issue by ftiguidou** [manuel-calzolari/sklearn-genetic#3]
Hello,

First thank you for your work which works really great !
I am trying to compare results going with different optimization parameters for my model. I would like to store for each value of this parameter the computed maximum score value obtained with the variable selection. I understood that the feature selection is stored in selector.support_, but where is the score value (ex: accuracy) obtained with this feature selection ?

Thank you

**Comment by manuel-calzolari** [comment]
I added a `generation_scores_` attribute, see d9604d2.
