### ISSUE TITLE
Feature_importance scores

### ISSUE THREAD

**Issue by talha33** [manuel-calzolari/sklearn-genetic#34]
is their any way to get the score of the each selected feature. need to plot a bargraph.

**Comment by manuel-calzolari** [comment]
The algorithm looks for a subset of features that maximizes a score, it does not inherently compute any measure of feature importance. What you can do is look at the feature importance of the model trained on the selected features.

**Comment by talha33** [comment]
Got That! Thank you so much for your time

**Comment by talha33** [comment]
one more question if you dont mind... what kind of fitness function is used here?

**Comment by manuel-calzolari** [comment]
It's the one you specify through the `scoring` parameter, with some exceptions (for example, individuals with an invalid number of features are artificially set to a very low score).
