### ISSUE TITLE
Request for new version release

### ISSUE THREAD

**Issue by paulduf** [manuel-calzolari/sklearn-genetic#43]
Hello, 

I have dependencies issues using the latest version of `sklearn`. I saw you addressed these in the latest commit https://github.com/manuel-calzolari/sklearn-genetic/commit/12ee9b2e591ec379793bcff1966095b43dac10c6.
Could you bump a new version release so that I can properly lock the dependencies versions of my project ?

Many thanks for making this package available.

**Comment by manuel-calzolari** [comment]
Hi @paulduf,

Thank you for your interest in the package!

I'm currently swamped with work and will be heading on vacation for the next two weeks. I'll try my best to release a new version tomorrow morning. If for some reason I'm unable to do so, please expect the release in late September when I return from vacation.

**Comment by RNarayan73** [comment]
@manuel-calzolari 
Looking forward to the release, hoping it addresses issue #45 that I just raised.

**Comment by manuel-calzolari** [comment]
Version 0.6.0 has been released
