### ISSUE TITLE
What is the difference and relationship between this repo and Sklearn-genetic-opt?

### ISSUE THREAD

**Issue by imxtx** [manuel-calzolari/sklearn-genetic#44]
Sklearn-genetic-opt: https://github.com/rodrigo-arenas/Sklearn-genetic-opt

**Comment by manuel-calzolari** [comment]
Hi @imxtx,

This project (sklearn-genetic) started over 7 years ago and was the first feature selection library for scikit-learn to utilize genetic algorithms (as far as I'm aware, it was also the first for Python in general). Another library, sklearn-deap (https://github.com/rsteca/sklearn-deap), existed for optimizing hyperparameters using genetic algorithms. The library you mentioned appears to combine both feature selection (similar to my project) and hyperparameter optimization (akin to sklearn-deap), and was released much later.

**Comment by imxtx** [comment]
I see, thank you.
