### ISSUE TITLE
Explain output when verbose=1

### ISSUE THREAD

**Issue by quique0194** [manuel-calzolari/sklearn-genetic#9]
I have the following output, Could you explain in the documentation what is the meaning of each column? Thanks!

![image](https://user-images.githubusercontent.com/4630204/71044946-32409a80-2101-11ea-81bf-1ac2788d5ef7.png)

**Comment by quique0194** [comment]
It seems like the format of the output is:
`[avg(scoring) avg(number_of_features)] [std(scoring) std(number_of_features)] [min(scoring) min(number_of_features)] [max(scoring) max(number_of_features)]`

And `-10000` is the score you get when the number of selected features is greater than the number of `max_features` you set.

So what is the purpose of setting max_features?

**Comment by manuel-calzolari** [comment]
Sorry for the extremely late reply.

`-10000` is a "bad score" that get assigned to invalid feature combinations to discourage their selection (combinations with a number of features > `max_features` are invalid).

It looks like, in your case, all the generated combinations are invalid (number of features > `max_features`). Commit 3d62422 should improve the situation by generating only valid combinations for the initial population.

Please feel free to reopen the issue if necessary.
